# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0ae06201e58608588699f6780fe0be9867c49394ea1887475ef18a2c959f76bc7fa2042d235cfac4b58ac8a32a6b370fe4c987379ab7f87fccc3dee6dcef87

test:
  secret_key_base: f1527500ce1cb07c69c11aa2acc57cc747fc16ef790863b26f5480ffe136830f7cb4fa56f619cdc46624da1c86e1ed04074fb6e629b9ce97a0908f7f0f1afe36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
